name:                concept
version:             0.1.0.0
github:              "githubuser/concept"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- cbits/sha256-sse41-sha-x86.c
- cbits/chacha_offset.c

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/concept#readme>

dependencies:
- base >= 4.7 && < 5
- base16
- basement
- bytestring
- cereal
- cryptonite
- memory
- mtl
- transformers
- optparse-applicative

library:
  source-dirs: src
  c-sources: 
    - cbits/chacha_offset.c
    - cbits/sha256-sse41-sha-x86.c
    - cbits/sha256.c
  cc-options: -msse4.1 -msha
  extra-libraries: sodium
  ghc-options:
    - -Wall
    #- -Werror
    - -O2

executables:
  tl:
    main:                Main.hs
    source-dirs:         app/tl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concept

  testtl:
    main:                Main.hs
    source-dirs:         app/testtl
    extra-libraries: 
    - tl-lib
    - arm-crypto
    - x86-sse41-sha
    - sha-cuda
    - cpu_features
    - cuew
    - stdc++
    extra-lib-dirs: 
    - tl-lib/build
    - tl-lib/build/sha256-impls/arm-crypto
    - tl-lib/build/sha256-impls/x86-sse41-sha
    - tl-lib/build/sha256-impls/sha-cuda
    - tl-lib/build/extern/cpu_features
    - tl-lib/build/extern/cuew
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concept
    - file-embed

tests:
  concept-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concept
    - hspec
