name:                concept
version:             0.1.0.0
github:              "githubuser/concept"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/concept#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- base16
- bytestring
- cereal
- cereal-conduit
- conduit
- containers
- cryptonite
- cryptonite-conduit
- deepseq
- file-embed
- filepath
- memory
- mtl
- text
- transformers
- optparse-applicative
- number-length

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  extra-libraries: 
    - arm-sha
    - x86-sha
    - cuda-sha
    - sha-generic
    - cpu_features
    - cuew
    - stdc++

executables:
  tl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concept
    - time

tests:
  concept-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concept
    - hspec

